apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
  namespace: dev
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: mycontainer
        image: "devopsjourney1/mywebapp:latest"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
          name: mykustom-map
    
            
