
resources: 
- app1-deployment.yaml
- app1-service.yaml

commonLabels:
  app: mykustomapp

commonAnnotations:
  app: mykustom-annontations

namePrefix:
  kustom-

nameSuffix:
  -v1

configMapGenerator:
- name: mykustom-map
  env: config.properties